### ISSUE TITLE
Problem with widget display on IOS

### ISSUE THREAD

**Issue by vfxbro** [SalihCanBinboga/info_popup#10]
Hello!
I use your package and I like everything. Thank you

I have a problem with displaying the widget on the iOS 16.2 platform
Widget content is cropped in height if the widget is at the bottom of the screen
Everything is fine on the Android platform.

I am attaching 2 screenshots, 1st screenshot from IOS, 2nd from Android.

How can I fix this?
![ios](https://github.com/SalihCanBinboga/info_popup/assets/4408699/6724c044-bd9f-4d5a-8334-79f9538228d1)
![android](https://github.com/SalihCanBinboga/info_popup/assets/4408699/a02eb4cf-f369-4209-9dbc-2f8cf29e67f0)

**Comment by SalihCanBinboga** [comment]
Hi @vfxbro, first of all, thank you for your feedback 🙏. Once we reproduce the issue, I will share the current status here

**Comment by SalihCanBinboga** [comment]
Could you try again with version 4.3.1 of the package? You can also check and adjust the added features according to your preferences. @vfxbro
