### ISSUE TITLE
Content refresh problem

### ISSUE THREAD

**Issue by giantss** [SalihCanBinboga/info_popup#11]
After changing the app language for nationalization, the content language in info_popup has not changed.

<img width="286" alt="image" src="https://github.com/SalihCanBinboga/info_popup/assets/13778798/882f295b-05a9-4127-a69c-f9123fdcb387">

**Comment by giantss** [comment]
@SalihCanBinboga  Can you help me find out what's going on? Will the content be cached?

**Comment by SalihCanBinboga** [comment]
I apologize for the late response; I've been quite busy lately. 
- Which package or structure are you using for localization?
- Even though you close and reopen the popup, is the localization not applied?

@giantss

**Comment by giantss** [comment]
It doesn't matter, I'm using `Getx`, I'm currently using  [custom_pop_up_menu,](https://pub.dev/packages/custom_pop_up_menu) it won't have this phenomenon.

**Comment by SalihCanBinboga** [comment]
Thank you for your feedback. This issue was solved with this [PR](https://github.com/SalihCanBinboga/info_popup/pull/14).
