### ISSUE TITLE
The popup cannot be closed by clicking the icon multiple times

### ISSUE THREAD

**Issue by giantss** [SalihCanBinboga/info_popup#12]
Phenomenon：

The first time you click on the icon, the popup will appear. If you click on the icon again, it will first close and then be displayed again. As a result, the popup cannot be hidden.

**Comment by SalihCanBinboga** [comment]
Closure of the popup when the expected behavior icon is clicked again, right? @giantss

**Comment by giantss** [comment]
https://github.com/SalihCanBinboga/info_popup/assets/13778798/bbbfbf0b-9add-48d3-b575-08f55b32792f

When the pop information is expanded and the user clicks pop again, I guess the user's purpose should be to close the current pop instead of popping it up again after closing.

**Comment by SalihCanBinboga** [comment]
Thank you for your feedback. This issue was solved with this [PR](https://github.com/SalihCanBinboga/info_popup/pull/14).
