### ISSUE TITLE
Arrow can't be white.

### ISSUE THREAD

**Issue by ChauCM** [SalihCanBinboga/info_popup#13]
For some reason, 
```
  arrowTheme: const InfoPopupArrowTheme(
                  color: Colors.white,
                ),
```
will remove the arrow, another color works

**Comment by SalihCanBinboga** [comment]
Are you using 'arrowPainter'? @ChauCM

**Comment by ChauCM** [comment]
No, InfoPopupWidget with customContent and a child with the field above. No other config.

Other color showing fine but white seem to turn into transparent.

**Comment by SalihCanBinboga** [comment]
Okay, could you please share an example of how to use Infopopup with me? @ChauCM

**Comment by ChauCM** [comment]
please try this @SalihCanBinboga 
```
       InfoPopupWidget(
                // not show arrow for some reason https://github.com/SalihCanBinboga/info_popup/issues/13
                arrowTheme: const InfoPopupArrowTheme(
                  color: Colors.white,
                ),
                dismissTriggerBehavior: PopupDismissTriggerBehavior.anyWhere,
                areaBackgroundColor: Colors.transparent,
                customContent: Container(
                    height: 70.h,
                    width: 190.w,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(16.r),
                      color: Colors.white,
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.15),
                          blurRadius: 40.r,
                        ),
                      ],
                    ),
                    child: const Text('Sample')),
                child: const Text('data'),
              ),
```

<img width="209" alt="image" src="https://github.com/SalihCanBinboga/info_popup/assets/86839861/ab21b200-db3e-43be-a7a2-e0d6223caeab">


change color to red:
<img width="203" alt="image" src="https://github.com/SalihCanBinboga/info_popup/assets/86839861/40e0e5f4-3981-4db5-9837-c28095d83008">

expect:
<img width="123" alt="image" src="https://github.com/SalihCanBinboga/info_popup/assets/86839861/0c70be00-02c3-4793-83d8-ec94ec6ddc83">

**Comment by SalihCanBinboga** [comment]
The thing is, there is an arrow visible there. Its visibility is so low because it is under the shadow of the Container widget. @ChauCM

**Comment by ChauCM** [comment]
@SalihCanBinboga why is it the case? How can I make the arrow above the Container shadow?
