### ISSUE TITLE
Option to close popup when click on specific element (such as a close 'X' button)

### ISSUE THREAD

**Issue by claudemircasa** [SalihCanBinboga/info_popup#15]
Please add described feature above. I need to create custom popups white custom body content and close with 'X' button.

I achieved this by defining a type from the _InfoPopupWidgetState class and creating a new method within this class called 'close()'. To access the method I used a global key.

**Comment by SalihCanBinboga** [comment]
Should you wish to add the feature you desire to the package, you can open a PR. We can take action quickly 💪 @claudemircasa
