### ISSUE TITLE
[Mobile - Android & iOS] Info popup hidden by keyboard

### ISSUE THREAD

**Issue by lucasarcouto** [SalihCanBinboga/info_popup#18]
Hi!

First of all, I wanna say I really appreciate the work that went into this package. I am in the process of integrating it into a project of mine and just noticed an issue with the positioning of the popup. 

### Issue
Whenever the keyboard is open and I try to open the popup, it gets hidden by it. There doesn't seem to have a way for me to force the widget to show above the button instead of below.

### Platforms
I can confirm this is happening both in Android and iOS as well as emulators and physical devices.

### Steps to reproduce
1 - Run code on Android/iOS emulator/simulator/physical device
2 - Tap the TextField to make the keyboard open up
3 - Tap the Info icon to open the popup

### Code
```import 'package:flutter/material.dart';
import 'package:info_popup/info_popup.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: InfoPopupPage(),
    );
  }
}

class InfoPopupPage extends StatefulWidget {
  const InfoPopupPage({super.key});

  @override
  State<InfoPopupPage> createState() => _InfoPopupPageState();
}

class _InfoPopupPageState extends State<InfoPopupPage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SafeArea(
        child: Column(
          children: <Widget>[
            Expanded(
              child: TextField(),
            ),
            InfoPopupWidget(
              contentTitle: 'Info Popup Icon Example',
              dismissTriggerBehavior: PopupDismissTriggerBehavior.anyWhere,
              arrowTheme: InfoPopupArrowTheme(
                color: Colors.pink,
              ),
              child: Icon(
                Icons.info,
                color: Colors.pink,
              ),
            ),
            SizedBox(height: 16),
          ],
        ),
      ),
    );
  }
}
```

**Comment by SalihCanBinboga** [comment]
Hello @lucasarcouto , first of all, thank you for using the package and providing feedback. Due to my busy schedule this month and the next, I won't be able to address this issue. If you can make the improvements yourself during this period, we can merge them into the package shortly. Wishing you a great day 👋

**Comment by fahami** [comment]
Any updates about this?
