### ISSUE TITLE
Need to add Pop bevaviour

### ISSUE THREAD

**Issue by kaushikbh99** [SalihCanBinboga/info_popup#20]
I have a close button (X) in the popup view, Now I want by tapping on this button then close the popup view.
I have put Inkwell on "X" button.
I have write InfoPopupWidget's customContent property.

```
 customContent: () => InkWell(
                  onTap: () async => await context.maybePop(),
                  child: Container())
```

**Comment by kaushikbh99** [comment]
> I have a close button (X) in the popup view, Now I want by tapping on this button then close the popup view. I have put Inkwell on "X" button. I have write InfoPopupWidget's customContent property.
> 
> ```
>  customContent: () => InkWell(
>                   onTap: () async => await context.maybePop(),
>                   child: Container())
> ```

@SalihCanBinboga is there any solution?

**Comment by SalihCanBinboga** [comment]
Hey @kaushikbh99 👋 You can close 'InfoPopupWidget' only with its own controller class of 'InfoPopup'. Therefore, you should keep the relevant controller by using this [callback](https://pub.dev/documentation/info_popup/latest/info_popup/InfoPopupWidget/onControllerCreated.html). Then to close pop use this [method](https://pub.dev/documentation/info_popup/latest/info_popup/InfoPopupController/dismissInfoPopup.html) with controller.
