### ISSUE TITLE
Only left edge shows popup

### ISSUE THREAD

**Issue by jodymac** [SalihCanBinboga/info_popup#3]
Using either a Text widget or icon widget in infoPopup, only the very left edge will trigger the popup.  Is their a way to make this wrap the entire widget so my mouse over will show the popup anywhere on that widget.

**Comment by SalihCanBinboga** [comment]
Thank you for your contribution 🙏. Please provide the following information to help me better understand your issue:

- A gif, video, or screenshot that illustrates the problem.
- The platform you are experiencing the problem on (e.g. Android, iOS, Web, etc.).
- The output of the command "flutter doctor -v"
- The version of the info_popup package you are using.

@jodymac

**Comment by jodymac** [comment]
I switched over to a different method.  But I believe the issue was I had the width of the field in my table too small.  The different method I went with also suffered left edge only and was fixed after I started playing with padding and with width values, I was able to create the popup by putting the cursor in the center of my icon.
