### ISSUE TITLE
VScode no hot reload

### ISSUE THREAD

**Issue by shmink** [SalihCanBinboga/info_popup#4]
### System info
macOS 12.6 (with M1 chip)
vscode: 1.75.1
dart vscode extension: 3.58
info_popup: ^2.4.6

---

Love the package. Only thing I've noticed is that when making changes to a pop up, there doesn't seem to be any hot reloading happening. After my changes I can do a normal reload and will then see the changes I made. Just wondered if this was a known thing?

**Comment by SalihCanBinboga** [comment]
Hi @shmink ,

Thank you for your kind words about the package. I wanted to let you know that I am aware of this issue and am working on a solution for it. It will be addressed in the next update of the package.

I appreciate you taking the time to report this issue, it's very helpful.

**Comment by shmink** [comment]
Awesome stuff 👍

Might I also ask for a bit of insight. I'd like to add a drop shadow to my popup info. I can do it easy enough when it's just the main rectangle of the popup but can't work out how to apply a drop shadow to the arrow part. Even then, I think it might be that the shadow of the box will be overlapping the widest part of the arrow and not look right.

**Comment by SalihCanBinboga** [comment]
> Awesome stuff 👍
> 
> Might I also ask for a bit of insight. I'd like to add a drop shadow to my popup info. I can do it easy enough when it's just the main rectangle of the popup but can't work out how to apply a drop shadow to the arrow part. Even then, I think it might be that the shadow of the box will be overlapping the widest part of the arrow and not look right.

How are you looking to add a shadow to the arrow, or were you able to add one? Sorry for the delay, I haven't been able to focus much on this side due to my workload.
